### ISSUE TITLE
ChassisBase and ModuleBase classes each have two methods for retrieving serial number

### ISSUE THREAD

**Issue by jleveque** [Azure/sonic-platform-common#119]
ChassisBase and ModuleBase classes have a `get_serial_number()` method. However, they both also inherit the `get_serial()` method from DeviceBase class.

The `get_serial_number()` method should be removed from these classes, and the inherited `get_serial()` method should be used, as it is common to all device subclasses.

**Comment by Piyushagg19** [comment]
@jleveque: Hi. I'd like to work on this issue.

**Comment by Piyushagg19** [comment]
@jleveque: ChassisBase and ModuleBase classes don't have get_serial_number() method. Can you please confirm if this issue is still open and not closed with #173 ?

**Comment by jleveque** [comment]
@Piyushagg19: Thanks for checking! It appears I resolved this via https://github.com/Azure/sonic-platform-common/pull/130, but did not link the PR to this issue.

**Comment by jleveque** [comment]
Fixed via https://github.com/Azure/sonic-platform-common/pull/130.
