### ISSUE TITLE
sffbase.py convert_hex_to_string method is throwing exception on str.strip operation after Python 3 migration

### ISSUE THREAD

**Issue by snider-nokia** [Azure/sonic-platform-common#160]
**return str.strip(binascii.unhexlify(ret_str))** is causing an exception such that SFP eeprom fields are not being populated properly.  This occurs because the str.strip exception is being returned from convert_hex_to_string instead of the properly converted value.

**Comment by jleveque** [comment]
@snider-nokia: I just found this issue myself a few days ago and opened [this PR](https://github.com/Azure/sonic-platform-common/pull/165) to fix. Please help test and review it.
